apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      serviceAccountName: php-ksa
      containers:
      - name: php-app
        image: phpmyadmin
        # This app listens on port 80 for web traffic by default.
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: PMA_HOST
          value: "set-by-proxy"
        - name: PMA_PORT
          value: "set-by-proxy"
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: php-secrets
              key: username
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: php-secrets
              key: password
        - name: PMA_PMADB
          valueFrom:
            secretKeyRef:
              name: php-secrets
              key: database
